title: "Buttons"
description: |
  Buttons should only be used when there are obvious actions that is required. They are primarily for call-to-actions for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      They are the default buttons. They should be used on primarily light backgrounds.
    fields:
      - name: text
        type: string
        example: "Learn More"
  ghost:
    title: "Ghost"
    description: |
      The ghost buttons are for call-to-actions on images and for optional actions.
    fields:
      - name: text
        type: string
        example: "Learn More"
  hamburger:
    title: "Hamburger"
    description: |
      The hamburger button is for the mobile version for the navigation bar.
  close:
    title: "Close"
    description: |
      The close button is for the mobile version for the navigation bar after clicking.
  instagram:
    title: "Instagram"
    description: |
      The Instagram button is to link to Instagram.
  github:
    title: "Github"
    description: |
      The Github button is to link to Github.
